### ISSUE TITLE
Controller input not recognized

### ISSUE THREAD

**Issue by RicardoASilva** [miroof/node-virtual-gamepads#1]
I installed node virtual gamepads for raspberry pi 2 following the instructions provided here https://github.com/RetroPie/RetroPie-Setup/wiki/Virtual-Gamepad.
After everything set up on emulationstation it detects all gamepads connected to the same webpage, but when i am on the input setup of the emulationstation and i try clicking on the buttons or anywhere on the gamepad its ignored.
I tried with chrome and firefox on desktop and IE on windows Phone.

**Comment by miroof** [comment]
Hi Ricardo,

Did you configure in EmulStation and with Retoarcharch config like with all other controller ?

This may helps you : http://blog.petrockblock.com/forums/topic/no-more-gamepad-why-not-use-the-phone/

**Comment by RicardoASilva** [comment]
Hi Miroof,

My issue is when i'm on the EmulationStation Configure input menu i get "1 gamepad detected" but when i try to hold any button on the web page the "virtual gamepad" text should appear but doesn't show up even tho i have the red color on the number 1 in the controller which is strange.
I cant get to the configuration step since it doesn't seem to recognize any button press :/ , i cant seem to find anyone with the same issue, not sure if i might be missing something.

Thanks for your help.

**Comment by RicardoASilva** [comment]
Ok finally got it working with an android on chrome seems to be the only way to do it.
