### ISSUE TITLE
Breaks on 64-bit machines

### ISSUE THREAD

**Issue by roba91** [miroof/node-virtual-gamepads#14]
`virtual_gamepad.sendEvent` breaks on 64-bit machines. It throws an `EINVAL` (errno 22). I assume this is caused by the fact that the `time` struct that is part of the `input_event` struct is composed of a `__kernel_time_t` and a `__kernel_suseconds_t` field. Both are defined as `long` (which has 32 bits for 32 bit systems and 64 for 64 bit systems).

By doing 

```
  input_event_end = Struct()
    .struct('time', Struct().word32Sle('tv_sec').word32Sle('tv_usec'))
    .word16Ule('type')
    .word16Ule('code')
    .word32Sle('value')
```

the Code will only work for 32 bit machines.

Changing both `word64Sle` to `word64Sle` fixes the problem for me but will probably (couldn't test) break on 32 bit machines.

**Comment by miroof** [comment]
Hi Rouven,

Thanks for your feedback, we need to find a solution which works on both
architectures.

I will take a look or at least mention your solution in the read me.

Thanks again,
Jeremy
Le mar. 16 août 2016 à 22:56, Rouven Bauer <notifications@github.com> a
écrit :

**Comment by dvanmilligan** [comment]
how do I get this to work with retro pie "retroarch" on a raspberry pi 3. I am able to access the controller on my phone but it is not detected by retroarch/retropie

**Comment by roba91** [comment]
@dvanmilligan: You may open a new issue for that and explain your problem in detail. The more information, the easier we can help you.

**Comment by roba91** [comment]
This module could possibly help: https://github.com/TooTallNate/ref-struct
