### ISSUE TITLE
Possible to switch server address?

### ISSUE THREAD

**Issue by Atrion** [miroof/node-virtual-gamepads#18]
Currently I run an apache server on my system as well as emulation station which I plan to use this virtual gamepad with. 
The address the controller will want to connect to is already in use is there a way to change the port or the server address?

**Comment by miroof** [comment]
Hi Atrion,

You can modify the port number in the **config.json** file before running virtual gamepad application.

Regards,
Jeremy

**Comment by roba91** [comment]
I guess this issue can be closed...
