### ISSUE TITLE
problème avec le devicename

### ISSUE THREAD

**Issue by rockaddicted** [miroof/node-virtual-gamepads#2]
Salut Miroof et merci pour le boulot effectué.
Nous sommes en train d'intégrer ton projet à la recalbox (mieux vaut tard que jamais ^^), mais nous avons un problème lors du mapping de la manette sous ES.
Le nom de device contient un caractère spécial ce qui fout la merde après dans le processus de configuration.
- extrait du fichier es_input.cfg : 

```
    <inputConfig type="joystick" deviceName="Virtual gamepad&#02;&#12;" deviceGUID="03000000030000000300000002000000">
        <input name="a" type="button" id="0" value="1" />
        <input name="b" type="button" id="1" value="1" />
        <input name="down" type="axis" id="1" value="1" />
        <input name="hotkey" type="button" id="6" value="1" />
        <input name="left" type="axis" id="0" value="-1" />
        <input name="pagedown" type="button" id="5" value="1" />
        <input name="pageup" type="button" id="4" value="1" />
        <input name="right" type="axis" id="0" value="1" />
        <input name="select" type="button" id="6" value="1" />
        <input name="start" type="button" id="7" value="1" />
        <input name="up" type="axis" id="1" value="-1" />
        <input name="x" type="button" id="2" value="1" />
        <input name="y" type="button" id="3" value="1" />
    </inputConfig>
```
- Ce qui nous donne sous jstest : 

```
[root@RECALBOX ~]# jstest /dev/input/js0 
Driver version is 2.1.0.
Joystick (Virtual gamepad
                          ) has 2 axes (X, Y)
and 8 buttons (BtnX, BtnY, BtnTL, BtnTR, BtnTR2, BtnSelect, BtnThumbL, BtnThumbR).
```

Une idée de la source du problème? As tu moyen de jeter un coup d’œil s'il te plaît?

**Comment by miroof** [comment]
Salut Rockaddicted,

Content de savoir que le projet va servir =)

Ça ne doit pas être bien méchant, je vais y jeter un oeil dès ce WE.

Bonne soirée,
Miroof

**Comment by rockaddicted** [comment]
Magnifique, merci bien =)

**Comment by digitalLumberjack** [comment]
Un petit coucou @miroof  en passant :) Tu viens plus sur l'irc ?

**Comment by bbk79** [comment]
Google translate is not too bad after all :)

I fixed this by terminating device name with a null character:

uidev.name = "Virtual gamepad\u0000";

(virtual_gamepad.coffee and virtual_gamepad.js)
