### ISSUE TITLE
virtual gamepad buttons should be labeled

### ISSUE THREAD

**Issue by cpcbegin** [miroof/node-virtual-gamepads#20]
Virtual gamepad, we see in recalbox.local:8080, should be all the buttons labeled at this web.
It's confused if you don't know the name of each button in original snes gamepad and I need see wiki in a paper or another mobile.

**Comment by roba91** [comment]
Do you know how to edit a vector graphic? Hint: Inkscape is quite a good program to do so. Just fork the project and edit `public/images/SNES_controller.svg`. Then create a pull request.

**Comment by miroof** [comment]
Hi,

As @roba91 said you can edit the SVG file by yourself and create a pull request. But yes you're right, it could be interesting to add this. I'll keep you issue opened.

Regards,
Mirof

**Comment by cpcbegin** [comment]
I get to change the SVG files and they show the labels, but I didn't create the pull request because although I can see ok opening directly in the navigator, I can't see the labels in recalbox (I copied these files in /usr/node-virtual-gamepads/public/images, I changed to read and write mode with 'mount -o remount, rw /')

I enclosed both files in this ZIP file:

[SNES_controllers.zip](https://github.com/miroof/node-virtual-gamepads/files/650234/SNES_controllers.zip)

**Comment by roba91** [comment]
That is strange. I honestly don't know too much about how recalbox handles things. Have you tried to start the server on your PC (the readme explains how to do so)?

**Comment by cpcbegin** [comment]
I install the server on my PC but the problem persists. I'm doing something wrong :(

**Comment by roba91** [comment]
Oh sorry. What I didn't see, is that the svg is actually copied into the html file.

I had a look at it and noticed that the button labels were actually included in the svg. The only problem was, that inkscape used `flow text` objects to place the text. But browsers can't handle them. So converting the `flow text` to simple `text` or `path`s fixed it. I'll open a merge request. Thanks for your effort!
