### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by simonhochrein** [miroof/node-virtual-gamepads#21]
Is there a way to use this for player 1 and player 2?

**Comment by roba91** [comment]
You can connect with two different devices/browsers. Then the first that connects will be controller for player 1 while the second one to be connected will be assigned as controller for player two.

You can do this for up to 4 players.

**Comment by simonhochrein** [comment]
Thanks!
I am using emulationstation on retropie and was also wondering how to set it up (commands and stuff)

**Comment by roba91** [comment]
If your question is answered you may close the issue.
