### ISSUE TITLE
Customize Gamepad controller

### ISSUE THREAD

**Issue by samukukez** [miroof/node-virtual-gamepads#24]
Hello.

How can I customize the Gamepad controller to add / quit buttons? (I have my design ready onto a .svg)

Thanks.

**Comment by roba91** [comment]
First question: does your platform support a quit button? If so, you need to find out which button this is or if it's freely assignable you can just choose a button that's not support by `node-virtual-gamepads` yet. The the next step is to modify the svg part that is embedded in `public/index.html` according to you new layout. Note that you have to add a few things manually. In the style of `id="btnQuit" class="btn" data-btn="path4756" data-code="0x136"` where data code is the event that will be sent to the server.

That should be it.

**Comment by roba91** [comment]
@samukukez could you make it work?

**Comment by roba91** [comment]
I'll close this issue for now. Feel free to reopen it if you need more support on this one.
