### ISSUE TITLE
How to switch from gamepad to keyboard views ?

### ISSUE THREAD

**Issue by rockaddicted** [miroof/node-virtual-gamepads#26]
Hi @roba91
This morning I wanted to try your virtual keyboard. So I built the recalbox branch on the last commit, but I must missing something.
I tried it in ES, and I was unable to "switch" on the keyboard view. I was only able to use the standard gamepad view.
What am I missing, please ?

**Comment by roba91** [comment]
You have to open `/keyboard `. There is currently no button for it. Please let me know as soon as you have merged the virtual keyboard into recalbox. I will then create a merge request to add a link to the recalbox manager.

**Comment by roba91** [comment]
I actually thought about a button to switch from gamepad to keyboard and vice versa. But I was afraid one could hit it accidentally while playing and not looking at the virtual gamepad. That would be really annoying in games, I guess.

**Comment by rockaddicted** [comment]
haha thank you dude, that works very well :smiley: 
I tested it in ES, then close ES, logged in root access on recalbox, and launched some basics commands.
Indeed a button to switch between gamepad/keyboard could be annoying in games.

Would it be possible to do the same than with the gamepad, a shortcut specific to the keyboard ? https://github.com/miroof/node-virtual-gamepads#use-it-as-standalone-application-chrome-mobile

Then let people switch between there 2 shortcuts virtual-gamepad / virtual-keyboard ?

About the merge in recalbox, that will be done soon. I seen you did a PR to add labeled gamepads on master branch. It could be great to have the same on recalbox branch, with the "customised" recalbox gamepad.

**Comment by roba91** [comment]
> About the merge in recalbox, that will be done soon. I seen you did a PR to add labeled gamepads on master branch. It could be great to have the same on recalbox branch, with the "customised" recalbox gamepad.

They should be mergable in a straight forward way. SVGs are luckily a text-based format. Thus, a merge of the branches should do the job.

**Comment by miroof** [comment]
I @roba91, @rockaddicted,

First sorry for my low availability, I'll try to be more active on this
project in a near future. I will handle the merge ASAP.

Have a good day,
Jeremy
Le dim. 18 déc. 2016 à 14:24, Rouven Bauer <notifications@github.com> a
écrit :

**Comment by roba91** [comment]
Should be closed with PR #29
