### ISSUE TITLE
`npm install` fail on Jessie

### ISSUE THREAD

**Issue by paulgeringer** [miroof/node-virtual-gamepads#28]
This is very similar to https://github.com/miroof/node-virtual-gamepads/issues/5 (though my french is a bit rusty). I was hitting the following error when running `npm install`:

```
> ioctl@1.0.1 install /home/retropie/node-virtual-gamepads/node_modules/ioctl
> node-gyp rebuild

make: Entering directory '/home/retropie/node-virtual-gamepads/node_modules/ioctl/build'
  CXX(target) Release/obj.target/ioctl/src/ioctl.o
In file included from ../src/ioctl.cpp:3:0:
../node_modules/nan/nan.h:324:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
ioctl.target.mk:82: recipe for target 'Release/obj.target/ioctl/src/ioctl.o' failed
make: *** [Release/obj.target/ioctl/src/ioctl.o] Error 1
make: Leaving directory '/home/retropie/node-virtual-gamepads/node_modules/ioctl/build'
```

The solution was to upgrade `node-gyp` to the latest version (found https://github.com/nodejs/nan/issues/414), after which `npm install` worked without errors. 

Not sure if there is anything to change with this project's setup, but I'm adding this issue just so anyone else who runs into this issue has a solution.

**Comment by roba91** [comment]
Would you be so kind to create a PR, adding this hint to `TROUBLESHOOTING.md`?

**Comment by robsdedude** [comment]
Closing this. I added a hint in `TROUBLESHOOTING.md` to check the issues.
