### ISSUE TITLE
node main.js version mismatch

### ISSUE THREAD

**Issue by Kandy84** [miroof/node-virtual-gamepads#44]
HI developers,    
I tried to add the virtual gamepad for retropie by the described steps:

    git clone https://github.com/miroof/node-virtual-gamepads
    cd node-virtual-gamepads
    npm install
    sudo node main.js

sudo node main.js  gives me  this error
```
pi@retropie:~/node-virtual-gamepads $ sudo node main.js                         
/home/pi/node-virtual-gamepads/node_modules/ioctl/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module version mismatch. Expected 14, got 46.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/pi/node-virtual-gamepads/node_modules/ioctl/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/pi/node-virtual-gamepads/node_modules/ioctl/index.js:1:94)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

also the /opt/retropie/configs/all/retroarch-joypads/Virtualgamepad.cfg
is missing and can´t access with the browser or smartphone via local address of my retropie

could anyone give me a hint how to get the virtual gamepad running?

Many thanks,
Andy

**Comment by roba91** [comment]
Please give more detail.
 - Which node version are you running (try `node -v` and `sudo node -v`)
 - Which version of npm is installed (try `npm -v` and `sudo npm -v`)

Another thing:  
Have you tried to follow these steps [https://github.com/RetroPie/RetroPie-Setup/wiki/Virtual-Gamepad](https://github.com/RetroPie/RetroPie-Setup/wiki/Virtual-Gamepad)? Because the installation instructions are slightly different (and that makes sens).

**Comment by Kandy84** [comment]
Hi roba91,
thanks for your answer.
Yes I followed  exactly these steps: https://github.com/RetroPie/RetroPie-Setup/wiki/Virtual-Gamepad

And these are my used versions of node and npm:

pi@retropie:~/node-virtual-gamepads $ sudo node -v
v0.12.6
pi@retropie:~/node-virtual-gamepads $ sudo npm -v
2.11.2

But I could not get access to the retropie via browser "http://192.168.1.XXX"
Do you have a hint for me?

**Comment by roba91** [comment]
Those are really old versions. Try updating node and npm:
```
sudo npm cache clean -f

# update node
sudo npm install -g n
sudo n stable

# update npm
sudo npm install -g npm
```

Now verify the verions with `sudo npm -v` and `sudo node -v`.

Then delete the folder `node_modules` that was created when you ran `npm install` the first time and re-run `sudo npm install` while you're in the folder into which you checked out this repo. Now try to start the gamepad with `sudo node main.js`

**Comment by Kandy84** [comment]
Hi roba,
many thanks for your help. Your are right my versions were really outdated :-) Now I have these two:
    pi@retropie:~/node-virtual-gamepads $ sudo node -v
    v0.12.6 -> v7.8.0
    pi@retropie:~/node-virtual-gamepads $ sudo npm -v
    2.11.2 -> 4.4.4
afterwards I ran this commands
```
rm node_modules -r
sudo npm install
sudo node main.js
```
and I had success :-))
Still 2 questions
1.  after reboot I have to run the "sudo node main.js" again to have the virtual gamepad running. Is there a possibility to have it runnig always after boot?
2. Why did I have these outdated versions of node and npm? I forced this command bring everything up-to-date "sudo apt-get update && sudo apt-get upgrade"

Thanks for your reply,
Andy

**Comment by roba91** [comment]
1. As written in https://github.com/RetroPie/RetroPie-Setup/wiki/Virtual-Gamepad you can use [PM2](https://www.npmjs.com/package/pm2) to do so. I'll copy over the steps from the tutorial:
   ```
   ### Enable Virtual Gamepad on Boot
   
   sudo npm install pm2 -g
   sudo pm2 start main.js
   sudo pm2 startup
   sudo pm2 save
   ```
2. God knows why the Ubuntu package repo (maybe others as well) have such a horribly outdated version of node and npm. This is just something you have to know. One should correct the tutorial on that point.
