### ISSUE TITLE
Chrome: Add to Home screen - Gamepad

### ISSUE THREAD

**Issue by cmstew** [miroof/node-virtual-gamepads#46]
Can't seem to get the add to home function working. I've included some pictures. The only thing I've modified is moving the app to port 8080 again because I want to run owncloud on port 80.

I've included 3 screenshots outlining the issue I'm having. Any ideas?

![screenshot_20170426-143043](https://cloud.githubusercontent.com/assets/8193597/25455530/64e6ecf4-2a8d-11e7-839f-83af3a4e84e1.png)
![screenshot_20170426-143050](https://cloud.githubusercontent.com/assets/8193597/25455532/6508b60e-2a8d-11e7-9b67-777631c7653b.png)
![screenshot_20170426-143059](https://cloud.githubusercontent.com/assets/8193597/25455531/6506927a-2a8d-11e7-9736-8ecce76f8f3a.png)

**Comment by roba91** [comment]
Which version are you running?

**Comment by cmstew** [comment]
Of the gamepad? I just checked, it's Version 1.2.1.

**Comment by cmstew** [comment]
Figured out the issue on my own. Not sure if this is a proper fix or not but it seems to have resolved my issue.

I removed the following line from the public/images/gamepad_icons/manifest.json:

`"start_url": "index.html"`

**Comment by cmstew** [comment]
So i found out that if you change it to the following, it works as well:

`"start_url": "/gamepad.html"`

I'm going to try to do a pull request with my fix. I'm still learning how to do all this stuff.
