### ISSUE TITLE
Left Shoulder

### ISSUE THREAD

**Issue by leoheck** [miroof/node-virtual-gamepads#49]
Hi, I just installed it with Retropie, running on my Nexus 6P I can't click on left shoulder button. Do you know about this issue?

**Comment by roba91** [comment]
Does all the rest work?
Have you seen the following?  
 ![gamepad layout](https://github.com/miroof/node-virtual-gamepads/blob/resources/schemas/touch_zones.png?raw=true)
The left shoulder button has a slightly unintuitive position to leave more space for the d-pad.

**Comment by leoheck** [comment]
@roba91 didn't notice LT was in the middle of the screen. I just searched for "left shoulder" and didn't thought to search for LT or something similar. I was testing it really quickly at 3 AM. My fault man. Thanks, I will close the issue when I test it properly.

**Comment by robsdedude** [comment]
I close this issue for now. If it's not working, feel free to reopen it.
