### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by MikaXII** [miroof/node-virtual-gamepads#5]
Yop Miroof.

Sans doute du a la nouvelle version de nodejs, mais impossible d'installer certains modules : 
- node v4.1.0
- npm v3.3.3

A savoir que sur la beta-6 de recalbox le virtualgamepad ne fonctionnerai pas.

un ptit bout log si ça peut t'aider : 
```
5950 error Linux 4.1.6-1-ARCH
5951 error argv "/usr/bin/node" "/usr/bin/npm" "install"
5952 error node v4.1.0
5953 error npm  v3.3.3
5954 error code ELIFECYCLE
5955 error ioctl@0.0.7 install: `node-gyp rebuild`
5955 error Exit status 1
5956 error Failed at the ioctl@0.0.7 install script 'node-gyp rebuild'.
5956 error This is most likely a problem with the ioctl package,
5956 error not with npm itself.
5956 error Tell the author that this fails on your system:
5956 error     node-gyp rebuild
5956 error You can get their info via:
5956 error     npm owner ls ioctl
5956 error There is likely additional logging output above.
5957 verbose exit [ 1, true ]
```

**Comment by miroof** [comment]
Salut MikaXII,

À première la solution serait de fixer la version de NodeJS. Je ne serais
pas dispo pendant une semaine, je regarde ça en rentrant de vacances !

**Comment by MikaXII** [comment]
J'ai trouvé le problème, c'est la version de ioctl dans le package.json qui n'est plus bonne.
Il faut remplacer : 
"ioctl": "~0.0.7", par  "ioctl": "~1.0.0",

**Comment by miroof** [comment]
Ok c'est mergé. Je ferais le diff sur le trunc à mon retour. Merci !
