### ISSUE TITLE
Webmanifest support

### ISSUE THREAD

**Issue by Tajnymag** [miroof/node-virtual-gamepads#58]
For the app to support adding to homescreen, it should include a manifest stating it's capabilities. Probably even a fullscreen option.

I'll forge a pull-request later this day.

**Comment by robsdedude** [comment]
You mean like those?
  - https://github.com/miroof/node-virtual-gamepads/blob/master/public/images/manifest.json
  - https://github.com/miroof/node-virtual-gamepads/blob/master/public/images/gamepad_icons/manifest.json
  - https://github.com/miroof/node-virtual-gamepads/blob/master/public/images/keyboard_icons/manifest.json
  - https://github.com/miroof/node-virtual-gamepads/blob/master/public/images/touchpad_icons/manifest.json

**Comment by Tajnymag** [comment]
Oh, dang it. Yes, that's what I meant.

Well, then it doesn't seem to work on Firefox for Android :D

**Comment by robsdedude** [comment]
It should work from FF 58 [1].

[1] https://hacks.mozilla.org/2017/10/progressive-web-apps-firefox-android/

**Comment by Tajnymag** [comment]
@robsdedude I know that it should, but I've just tried it on Firefox for Android 60 and it doesn't :D

I'll experiment with different properties on my own and will come back with my findings.
