### ISSUE TITLE
EmulationStation is asking for too many keys

### ISSUE THREAD

**Issue by dnk8n** [miroof/node-virtual-gamepads#7]
Using RetroPie 3.1

Followed instructions at https://github.com/RetroPie/RetroPie-Setup/wiki/Virtual-Gamepad

I don't get the same prompts as you do in https://www.youtube.com/watch?v=eH355PU2Eac. It asks for left thumb, etc. I don't know of a way to skip these keys.

Is there a manual way to configure controls?

**Comment by jakkn** [comment]
It says so in the configure menu; "HOLD ANY BUTTON TO SKIP"

**Comment by roba91** [comment]
I think this issue can be closed.
