### ISSUE TITLE
Mise a jour recalbox et probleme ioctl

### ISSUE THREAD

**Issue by digitalLumberjack** [miroof/node-virtual-gamepads#8]
Salut miroof, je suis entrain de mettre a jour le systeme et virtual-gamepad me fait ca, lorsque je me connecte depuis mon navigateur : 
/usr/node-virtual-gamepads/node_modules/ioctl/index.js:9
        throw e;
              ^
Error: ioctl -25
    at module.exports (/usr/node-virtual-gamepads/node_modules/ioctl/index.js:6:17)
    at /usr/node-virtual-gamepads/app/virtual_gamepad.js:30:13
    at FSReqWrap.oncomplete (fs.js:95:15)

T'as une idée de quoi ca peut venir ?

**Comment by miroof** [comment]
Salut Lumberjack,

Je jette un coup d'œil au plus vite (pas avant demain au boulot pcq je n'ai
pas de PC perso).

Miroof

**Comment by miroof** [comment]
Salut Lumberjack,

Qu'as-tu mis à jour exactement ? La version de Node ?

**Comment by digitalLumberjack** [comment]
Salut, c'est toujours la même version de node (0.12.7), j'ai mis a jour le buildroot tout entier (donc pas mal de logiciels on été updaté).

**Comment by roba91** [comment]
@digitalLumberjack, have you been able to solve this problem?

**Comment by MikaXII** [comment]
It's solved for a long time ago :) but there are new error.
