### ISSUE TITLE
Deactivate autostart

### ISSUE THREAD

**Issue by Silthrim** [miroof/node-virtual-gamepads#9]
How can I deactivate the autostart of the Virtual Gamepad and what is the command to start it manually?

**Comment by digitalLumberjack** [comment]
If you are talking about the integration of virtual gamepads in a distribution, it's not the good place to create an issue. The virtualgamepad do not start automatically, you must start it with `sudo node main.js` as it is written on the README

**Comment by Silthrim** [comment]
Hi thanks for the quick answer!
i installed it as a experimental package within the RetroPie Setup. in my case it starts on boot.
I think it automatically used the commands from the README.
How can I change it back to manually?
thanks for the answer!

**Comment by Silthrim** [comment]
I'm sorry, I think that this is not really an Issue, but I didn't found a comment section and it is in my opinion helpful so that other can this this to. I hope it doesn't bother too much

**Comment by digitalLumberjack** [comment]
Here is what is done: https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/virtualgamepad.sh

maybe you could delete it with pm2 delete

**Comment by Silthrim** [comment]
I tried sudo pm2 delete, but it gave this output:

error: missing required argument `name|id|script|all|json|stdin'

any idea?

**Comment by Silthrim** [comment]
deleting /etc/init.d/pm2-init.sh helped to stop it from autostarting and sudo node main.js helped to start it manually as you said. thanks for your help!

**Comment by roba91** [comment]
If your question is answered, you may close the issue.
